from .lora_loader import XBHHMultiLoraLoader
from .lora_loader_plus import XBHHMultiLoraLoaderPlus, NODE_CLASS_MAPPINGS as LP_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LP_NODE_DISPLAY_NAME_MAPPINGS
from .preset_selector import PresetSelector, NODE_CLASS_MAPPINGS as PS_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PS_NODE_DISPLAY_NAME_MAPPINGS
from .example_node import PromptRandomizer, NODE_CLASS_MAPPINGS as PR_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PR_NODE_DISPLAY_NAME_MAPPINGS
from .xlsx_viewer import XBHHXlsxViewer, NODE_CLASS_MAPPINGS as XV_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as XV_NODE_DISPLAY_NAME_MAPPINGS
from .xbhh_txt_selector import XBHHTxtSelector, NODE_CLASS_MAPPINGS as TS_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TS_NODE_DISPLAY_NAME_MAPPINGS
from .note_node import XBHHNoteNode, NODE_CLASS_MAPPINGS as NN_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as NN_NODE_DISPLAY_NAME_MAPPINGS
from .empty_latent import XBHHEmptyLatent, NODE_CLASS_MAPPINGS as EL_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as EL_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    "XBHHMultiLoraLoader": XBHHMultiLoraLoader,
    **LP_NODE_CLASS_MAPPINGS,
    **PS_NODE_CLASS_MAPPINGS,
    **PR_NODE_CLASS_MAPPINGS,
    **XV_NODE_CLASS_MAPPINGS,
    **TS_NODE_CLASS_MAPPINGS,
    **NN_NODE_CLASS_MAPPINGS,
    **EL_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "XBHHMultiLoraLoader": "XBHH Multi Lora Loader 🎨",
    **LP_NODE_DISPLAY_NAME_MAPPINGS,
    **PS_NODE_DISPLAY_NAME_MAPPINGS,
    **PR_NODE_DISPLAY_NAME_MAPPINGS,
    **XV_NODE_DISPLAY_NAME_MAPPINGS,
    **TS_NODE_DISPLAY_NAME_MAPPINGS,
    **NN_NODE_DISPLAY_NAME_MAPPINGS,
    **EL_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]

